# Generated by Django 5.1.7 on 2025-03-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_items',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
