# Generated by Django 5.1.7 on 2025-03-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_profile_saved_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
