# Generated by Django 5.1.7 on 2025-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_average_rating_product_total_people_rated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_1_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_2_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_3_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_4_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_5_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
