# Generated by Django 5.1.7 on 2025-04-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_invoice_id_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
