# Generated by Django 5.1.7 on 2025-04-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('PayPal', 'PayPal'), ('Stripe', 'Stripe'), ('COD', 'Cash On Delivery'), ('NA', 'Pending')], default='PayPal', max_length=6),
            preserve_default=False,
        ),
    ]
