# Generated by Django 5.1.7 on 2025-04-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(default='NA', max_length=2000),
            preserve_default=False,
        ),
    ]
