# Generated by Django 5.1.7 on 2025-04-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='billing_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='billing_full_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='billing_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.EmailField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_full_name',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(default='NA', max_length=10),
            preserve_default=False,
        ),
    ]
