# Generated by Django 5.1.7 on 2025-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_email_order_billing_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processed', 'Processed')], default='Pending', max_length=20),
        ),
    ]
